### ISSUE TITLE
Using "must not wrap retrieved config values" seems too restrictive.

### ISSUE THREAD

**Issue by ricog** [beporter/CakePHP-EnvAwareness#3]
Very good talk today. I only had one comment.

_The app must not wrap retrieved config values in conditionals._

I agree with what you are saying in general (you clarify it in the next sentence), but there are cases where you want to ensure they are defined, like `Google.Analytics.tracking_id`. And it seems there must be cases where the logic gets too complex to avoid an if/else or switch dependent on config.

So "must not wrap" might be better worded as "should avoid wrapping".

**Comment by beporter** [comment]
I'm not sure I agree. Why not place the GA code in an element, and load the element using a name stored in the configs? 

``` php
<?php echo $this->element(Configure::read('Google.Analytics.ElementName')); ?>
```

In a development environment, define the name as an empty or dummy element to load instead of the one with the tracker code. To me this is still just basic Themes stuff at its core. 

I'm not saying there might not be exceptions, but I suspect there are fewer than you might think there are.

I'm happy to discuss more though as this example illustrates how REALLY sticking to the rule (seems to) result in cleaner design almost without fail. 

---

And to be fair, I had a conversation with @jtyost2 about how:
- "must" really means "you REALLY should try"

and how 
- "should" really means "this would be a good idea if something in your setup doesn't stop you."

But I get what you're saying.

**Comment by ricog** [comment]
The element example seems like you are jumping through hoops just to respect the rule. And then it breaks badly if the element doesn't exist or your ElementName = ''. I think the configuration should be as simple as possible. A GA code or an `enabled` switch in the config is easier than needing to know which Google Analytics elements exist.

**Comment by beporter** [comment]
You can still store the GA property code in Configure too of course, but the entire Javascript snippet itself that should (or shouldn't) be included in page output is the very thing that is environment-dependent, not just the property code. If I was **really** jumping through hoops, I might suggest putting the entire GA code block in a Configure key. The element name is just a convenient shortcut for that, since the line between a Configure value and a big chunk of "themed" output is blurry here.

:shrug: I guess what you call "jumping through hoops" I call "proper design refactoring". IMO, you end up with a cleaner and more maintainable design. _"Don't do something different based on a config value; do the same thing using the different values."_ I can't restate it any more simply than that. You always want to include "tracking code" in the page, it's just that in some environments you want that "tracking code" to have no practical effect.

Like I said, all of the "must"s are really just "should"s anyway-- I can't force anyone to follow all (or any) of them, but I do maintain that making a stronger attempt to follow that particular guideline, instead of immediately resorting to an 

``` php
if(Configure::read('GA.enabled')) {
    echo $this->element('ga-js-block');
}
```

approach, will result in a design that's actually easier to maintain in the long run.

Thanks for the thoughts. Please keep them coming. Unless you'd prefer to keep the conversation private, feel free to use Github Issues for the repo too. Justin did that yesterday after the call. I like the idea of developing and discussing even the talk itself in the open.

**Comment by ricog** [comment]
Seems like we are nearly in agreement. Good discussion.

I'll use Issues going forward. If you like, we can regenerate this thread in Issues (one reply at a time per person) just so it's in there.

**Comment by beporter** [comment]
Yeah I like that idea. I think that means you get to go first. :smile:
